version: "3"

services:
  sportshoppoc-postgres:
    image: postgres:13-alpine
    container_name: sportshoppoc-postgres
    environment:
      - POSTGRES_DATABASE=sportshoppoc_dev
      - POSTGRES_USER=adminDev
      - POSTGRES_PASSWORD=poc_dev
    ports:
      - 5432:5432
    volumes:
      - postgres-sportshoppoc-data:/data/db
    restart: on-failure

volumes:
  postgres-sportshoppoc-data: